[package]
name = "sdkwork-api-customerservice-assembly"
edition.workspace = true
license.workspace = true
version.workspace = true
description = "Generated API assembly for sdkwork-customerservice application HTTP plane."

[lib]
name = "sdkwork_api_customerservice_assembly"
path = "src/lib.rs"

[dependencies]
axum.workspace = true
tokio.workspace = true
sdkwork-web-bootstrap.workspace = true
sdkwork-web-core.workspace = true
sqlx = { workspace = true }
sdkwork_customerservice_service_host = { workspace = true }
sdkwork-database-sqlx = { workspace = true }
sdkwork_routes_customerservice_app_api = { workspace = true }
sdkwork_routes_customerservice_backend_api = { workspace = true }
sdkwork_routes_customerservice_internal_api = { workspace = true }

[dev-dependencies]
sdkwork_communication_customerservice_service = { workspace = true, features = ["test-support"] }
sdkwork_customerservice_database_host = { workspace = true, features = ["test-support"] }
sdkwork_iam_context_service.workspace = true
serde_json.workspace = true
tower.workspace = true
uuid.workspace = true
